-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 14:36:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema food
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `food` ;

-- -----------------------------------------------------
-- Table `food`.`TRX_MAIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`TRX_MAIN` ;

CREATE TABLE IF NOT EXISTS `food`.`TRX_MAIN` (
  `TRX_ID` INT NOT NULL AUTO_INCREMENT,
  `CHECKOUT_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `TOTAL` INT NOT NULL,
  PRIMARY KEY (`TRX_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `food`.`PRODUCT` (
  `PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` VARCHAR(45) NULL,
  `PRICE` INT NULL,
  `PIC` VARCHAR(2000) NULL,
  PRIMARY KEY (`PRODUCT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food`.`TRX_DETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`TRX_DETAIL` ;

CREATE TABLE IF NOT EXISTS `food`.`TRX_DETAIL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TRX_ID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `QTY` INT NOT NULL,
  `PRICE` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_td_trx_id_idx` (`TRX_ID` ASC) VISIBLE,
  INDEX `fk_td_product_id_idx` (`PRODUCT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_td_trx_id`
    FOREIGN KEY (`TRX_ID`)
    REFERENCES `food`.`TRX_MAIN` (`TRX_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_td_product_id`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `food`.`PRODUCT` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
